name: C/C++ CI

on:
  push:
    branches: [ "master", "testing" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (hunspell, ncurses)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libhunspell-dev \
            libncurses-dev \
            pkg-config

      - name: make
        run: make

